create database college;
use college;
create table student(enrollment_num int, full_name char(20), gender char(1), age int, branch char(10));
desc student;
insert into student values(34, "Garvit", "M", 18, "CSE");
insert into student values(44, "Aayushi", "F", 17, "EC");
insert into student values(47, "Kratik", "M", 19, "ME");
insert into student values(59, "Diksha", "F", 18, "AU");
insert into student values(39, "Gaurav", "M", 18, "CSBS");
insert into student values(67, "Mohit", "M", 19, "IT");
insert into student values(140, "Ram", "M", 18, "CSE");
insert into student values(150, "Devansh", "M", 19, "ME");
insert into student values(155, "Shruti", "F", 19, "CE");
insert into student values(156, "Shruti", "F", 19, "CSE");
insert into student values(159, "Dipika", "F", 19, "IT");
insert into student values(170, "Saksh", "F", 18, "AU");
create table faculty(Faculty_id mediumint, Name char(30), Gender char(1), Age int, branch char(10), Salary float(5, 2), Year_joined year);
desc faculty;
insert into faculty values(101, "Rohit Mahajan", "M", 30, "ME", 344.9,'2008');
insert into faculty values(106, "Monika Jain", "F", 25, "CSE", 548.0,'2009');
insert into faculty values(102, "Kiran Talwariya", "F", 34, "IT", 783.0,'2012');
insert into faculty values(110, "Jitendra Sharma", "M", 45, "CE", 993.0,'2005');
insert into faculty values(107, "Sheetal Agrawal", "F", 40, "AU", 678.0,'2009');
insert into faculty values(105, "Rahul Sharma", "M", 51, "ME", 693.0,'2010');
SELECT full_name FROM student WHERE EXISTS (SELECT branch  FROM faculty WHERE  age=25 );
SELECT full_name FROM student WHERE branch=ANY (SELECT branch  FROM faculty WHERE  age>38 );
SELECT full_name FROM student WHERE branch=ALL (SELECT branch  FROM faculty WHERE  Gender="F" );
